
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lixwfyikorrtrxvpzfvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpeHdmeWlrb3JydHJ4dnB6ZnZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDUwODIsImV4cCI6MjA2MjQ4MTA4Mn0.M9IUko7SpX03_Lo4klt08fiL4urIM08cUK_Cu3tEtLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
